//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapEntityExemple
{
    using System;
    using System.Collections.Generic;
    
    public partial class stagiare
    {
        public int idStagiare { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> Age { get; set; }
        public int idFormation { get; set; }
    
        public virtual formation formation { get; set; }
    }
}
